// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.shield.optoutstudies.enabled", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1538826195);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1538826315);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1538825835);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1538826075);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1538825955);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1538826555);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1538826435);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 266240);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1538825805);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 66);
user_pref("browser.newtabpage.activity-stream.impressionId", "{2b9b77b4-4135-4611-89f0-b3628f87490e}");
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1538776800);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 3);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.onboarding.notification.last-time-of-changing-tour-sec", 1538825821);
user_pref("browser.onboarding.seen-tourset-version", 2);
user_pref("browser.onboarding.tour-type", "new");
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"sendToDevice\",\"pocket\",\"screenshots\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 8);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1538825812572");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1538829412572");
user_pref("browser.search.countryCode", "PL");
user_pref("browser.search.region", "PL");
user_pref("browser.slowStartup.averageTime", 1943);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20180907092132");
user_pref("browser.startup.homepage_override.mstone", "60.2.0");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"toolbar-menubar\":[\"menubar-items\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\"],\"currentVersion\":14,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1538825810410");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.iniFile.exists.appversion", "60.2.0");
user_pref("distribution.iniFile.exists.value", false);
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.lastModified", "Tue, 18 Sep 2018 22:29:12 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 25);
user_pref("extensions.getAddons.cache.lastUpdate", 1538826196);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "60.2.0");
user_pref("extensions.lastPlatformVersion", "60.2.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"screenshots@mozilla.org\":\"d568b079-1d6f-4da4-8cd9-36bf54c76fa3\"}");
user_pref("gecko.handlerService.migrated", true);
user_pref("media.gmp-manager.buildID", "20180907092132");
user_pref("media.gmp-manager.lastCheck", 1538826195);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.initialized", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 55515);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("security.sandbox.content.tempDirSuffix", "beebdc45-676f-42e1-bf5c-ee68be5be62c");
user_pref("services.blocklist.addons.checked", 1538768510);
user_pref("services.blocklist.clock_skew_seconds", 57805);
user_pref("services.blocklist.gfx.checked", 1538768510);
user_pref("services.blocklist.last_etag", "\"1538485002150\"");
user_pref("services.blocklist.last_update_seconds", 1538768510);
user_pref("services.blocklist.onecrl.checked", 1538768510);
user_pref("services.blocklist.pinning.checked", 1538768510);
user_pref("services.blocklist.plugins.checked", 1538768510);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1538825804);
user_pref("toolkit.telemetry.cachedClientID", "b5ef2c0b-21ea-439f-a3b6-f1ad91d49530");
user_pref("toolkit.telemetry.previousBuildID", "20180907092132");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
